### ISSUE TITLE
`auth=None` raises `AttributeError: 'NoneType' object has no attribute '__call__'`

### ISSUE THREAD

**Issue by imperosol** [eadwinCode/django-ninja-extra#106]
Versions :
- Python : 3.11
- Django : 5.0
- ninja : 1.1
- ninja-extra : 0.20
- ninja-jwt : 5.2

I tried settting up a global JWT authentication to my API, as following :
```python
# urls.py

from ninja_extra import NinjaExtraAPI
from ninja_jwt.authentication import JWTAuth
from ninja_jwt.controller import NinjaJWTDefaultController

api = NinjaExtraAPI(title="...", version="1.0.0", auth=JWTAuth())
api.auto_discover_controllers()
api.register_controllers(NinjaJWTDefaultController)
```
However, this brings the issue that the JWT controller is also locked behind JWT auth. Hence I tried to disable authentication checks for this controller :
```python
# api.py

@api_controller("/token", permissions=[AllowAny], tags=["token"], auth=None)
class AuthController(TokenVerificationController, TokenObtainPairController):
    """Overriden controller for obtaining and refreshing tokens"""
``` 
This is just a copy-paste of `NinjaJWTDefaultController`, with `auth=None` added (according to [django ninja's docs](https://django-ninja.dev/guides/authentication/#global-authentication)). After declaring this class, I unregistered the default NinjaJWTDefaultController.

However, this gives me the following error :
```
  File "<project directory>/api.py", line 17, in <module>
    @api_controller("/token", permissions=[AllowAny], tags=["token"], auth=None)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<poetry env directory>/ninja_extra/controllers/base.py", line 537, in _decorator
    return APIController(
           ^^^^^^^^^^^^^^
  File "<poetry env directory>ninja_extra/controllers/base.py", line 319, in __init__
    _call_back = _auth if inspect.isfunction(_auth) else _auth.__call__
                                                         ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '__call__'. Did you mean: '__bool__'?
```

This may be an inconsistence between ninja and ninja-extra api.

**Comment by eadwinCode** [comment]
@imperosol this will be resolved in the next release.

**Comment by imperosol** [comment]
Just saw the release. That's great. Thank you very much.

**Comment by eadwinCode** [comment]
@imperosol You are welcome
