### ISSUE TITLE
Error when using ModelController

### ISSUE THREAD

**Issue by TianaNanta** [eadwinCode/django-ninja-extra#134]
`/usr/local/lib/python3.11/site-packages/ninja_extra/pagination.py:90: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'app.mail.models.MailModel'> QuerySet.`
I get this error when using the method GET all (list) in the ModelController method, can anyone help me?

**Comment by eadwinCode** [comment]
@TianaNanta Can I see your ModelController setup?

**Comment by TianaNanta** [comment]
![Screenshot from 2024-05-03 21-40-27](https://github.com/eadwinCode/django-ninja-extra/assets/75852322/77899245-9674-46b5-8cd9-f194ebff0abf)
I set it like this

**Comment by eadwinCode** [comment]
Okay, it's a warning... You need to provide an order by attribute in your model.

**Comment by TianaNanta** [comment]
Ah okey, thank you

**Comment by eadwinCode** [comment]
You are welcome
