### ISSUE TITLE
Handle authentication errors in async routes with proper exceptions

### ISSUE THREAD

**Issue by mikaelsoudev** [eadwinCode/django-ninja-extra#135]
I have encountered difficulties while trying to handle the `ninja.errors.AuthenticationError` exception in asynchronous routes. Upon investigation, I identified a potential cause of the issue in the `AsyncOperation` class within the `operation.py`file.

Relevant Code:

```python

async def _run_authentication(self, request: HttpRequest) -> Optional[HttpResponse]:  # type: ignore
        for callback in self.auth_callbacks:
            try:
                is_coroutine = getattr(callback, "is_coroutine", False)
                if is_coroutine:
                    result = await callback(request)
                else:
                    result = callback(request)
            except Exception as exc:
                return self.api.on_exception(request, exc)

            if result:
                request.auth = result  # type: ignore
                return None
        return self.api.create_response(request, {"detail": "Unauthorized"}, status=401)

```

Identified Problem:

Currently, the _run_authentication method directly returns an HTTP response with a status 401 (Unauthorized) when authentication fails. This differs from the behavior in synchronous routes, where a specific exception is thrown.

Suggested Improvement:

To maintain consistency between synchronous and asynchronous routes, I suggest modifying the implementation to throw the AuthenticationError exception instead of directly returning the HTTP response. This would align error handling across different types of routes and improve centralized exception management.

**Comment by eadwinCode** [comment]
@mikaelsoudev I am working on resolving this shortly. Good work on investigating the problem. Thanks

**Comment by eadwinCode** [comment]
@mikaelsoudev Kindly close this issue if the issue is resolved

**Comment by mikaelsoudev** [comment]
Thank you very much, the solution worked perfectly.

We are currently deploying the tool in production at a major Brazilian company. We plan to contribute to the project's development as soon as we decide on its permanent adoption and deepen our understanding of the technology.

**Comment by eadwinCode** [comment]
Awesome @mikaelsoudev. Well done. I will be looking forward to that
