### ISSUE TITLE
Error Handling : Custom Exception message does not work

### ISSUE THREAD

**Issue by Jocelyn-AGORO** [eadwinCode/django-ninja-extra#140]
When defining a custom Error class which extends APIException,
when raising the exception, we got  : 
{
  "detail": "A server error occurred."
}

instead of the custom message of the exception

![exceptions](https://github.com/eadwinCode/django-ninja-extra/assets/61328035/6081ebc0-de1f-49af-833e-db9fc092fa91)

![api_exception](https://github.com/eadwinCode/django-ninja-extra/assets/61328035/28ccc5e1-b975-4320-ad9b-58b541431085)

![swagger_error](https://github.com/eadwinCode/django-ninja-extra/assets/61328035/a49e10c9-aea9-4386-9718-3d868fbf90c5)

**Comment by eadwinCode** [comment]
@Jocelyn-AGORO 
```python
class BadRequestException(APIException):
    status_code = status.HTTP_400_BAD_REQUEST
    default_detail = "Bad Request: " 
    
```
`message` should be changed to `default_detail`

**Comment by Jocelyn-AGORO** [comment]
Ok, I try it it works now. Thank You.
You need to change it on the documentation.

![doc_error](https://github.com/eadwinCode/django-ninja-extra/assets/61328035/cb3519bd-a41f-41b4-86f7-06a1b9b3a250)
[https://eadwincode.github.io/django-ninja-extra/tutorial/custom_exception/](url)

**Comment by eadwinCode** [comment]
Oh I see... Thanks @Jocelyn-AGORO

**Comment by eadwinCode** [comment]
@Jocelyn-AGORO This is now resolved
