### ISSUE TITLE
`@csrf_exempt` seems not working with `api_controller`

### ISSUE THREAD

**Issue by Tragio** [eadwinCode/django-ninja-extra#146]
Hi @eadwinCode 👋 

Thank you for your awesome work!! 🚀 

I was trying to enable `@csrf_exempt` inside my `api_controller` but couldn't find a way to make it work. Also searched in the docs and here on Github, but couldn't find any direction.

Not sure if it is a bug or if I'm not implementing it correctly.

```py
@api_controller("/auth", tags=["Auth"])
class AuthAPI:
    @http_post("/logout", response={status.HTTP_204_NO_CONTENT: None})
    @csrf_exempt
    def logout_user(self, request):
        logout(request)
        return None
```

Thank you very much 🙏

**Comment by eadwinCode** [comment]
@Tragio Did you do this
```python
api = NinjaExtraAPI(title='My Title', csrf=True)
```
As said [here](https://django-ninja.dev/reference/csrf/#use-an-authentication-method-not-automatically-embedded-in-the-request)

**Comment by Tragio** [comment]
Hi @eadwinCode 🙂 

I'm using this:
```py
api = NinjaAPI(auth=django_auth)
```

So it already comes with the CSRF enabled by default. What I need is to **not** need the CSRF to logout 🤔 there are been cases where the CSRF token disappeared, and I still want to logout.

**Comment by eadwinCode** [comment]
A lot is going on with CSRF for Django-Ninja. Check out this [issue](https://github.com/vitalik/django-ninja/issues/1101)

From what I have seen on the code, all ninja routes are exempted from CSRF middleware defined in settings.MIDDLEWARES because at the point of running the middleware, the callback is not the real endpoint handler but a Ninja PathView, and by setting `csrf=True`, Django-Ninja will manually rerun the CSRF middleware with the real callback.

**Comment by eadwinCode** [comment]
maybe you should try setting `csrf=True` and see if that works for you

**Comment by Tragio** [comment]
@eadwinCode I tried your suggestion, but the behaviour is the same 🤔

**Comment by eadwinCode** [comment]
@Tragio I checked with postMan and with csrf=True, it worked. When I removed csrf=True, it was as if CRSF was not applied to the routes

**Comment by Tragio** [comment]
@eadwinCode with

```py
api = NinjaExtraAPI(auth=django_auth)
```
and 

```py
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]
```

The CSRF work always as intended, but not the `csrf_exempt` 🤔

**Comment by eadwinCode** [comment]
@Tragio Django-Ninja does not work with CSRF Middleware registered in `MIDDLEWARE` when executing any `api` operation. Also during request, Django CSRF Middleware will always work fine and authenticated users will be identified. But until you set `api = NinjaExtraAPI(auth=django_auth, csrf=True)`, CSRF check will not apply to `api` operations

**Comment by Tragio** [comment]
@eadwinCode ahhhh I got what you mean now, so sorry 😅 🙏 

```py
@api_controller("/auth", tags=["Auth"])
class AuthAPI:
    @http_post("/login", auth=None, response={status.HTTP_204_NO_CONTENT: None})
    @csrf_exempt
    def login_user(self, request, payload: LoginSchema):
        user = authenticate(**payload.dict())

        if user is not None and user.is_active:
            login(request, user)
            return None

        raise HttpError(status.HTTP_401_UNAUTHORIZED, _("Invalid credentials"))
```

In your test, did you try with the `@api_controller`? 🤔 

```
Traceback (most recent call last):
  File "/Users/xyz/app/.venv/lib/python3.12/site-packages/ninja_extra/operation.py", line 193, in run
    result = self.view_func(request, **values)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xyz/app/.venv/lib/python3.12/site-packages/ninja_extra/controllers/route/route_functions.py", line 89, in as_view
    result = self.route.view_func(
             ^^^^^^^^^^^^^^^^^^^^^
TypeError: AuthAPI.login_user() got multiple values for argument 'request'
```

**Comment by eadwinCode** [comment]
```python
@api_controller("/auth", tags=["Auth"])
class AuthAPI:
    @http_post("/login", auth=None, response={status.HTTP_204_NO_CONTENT: None})
    @csrf_exempt
    def login_user(self, payload: LoginSchema):
        request = self.context.request
        user = authenticate(**payload.dict())

        if user is not None and user.is_active:
            login(request, user)
            return None

        raise HttpError(status.HTTP_401_UNAUTHORIZED, _("Invalid credentials"))
```
`request` is available at `self.context.request`

**Comment by Tragio** [comment]
So it solved the `got multiple values for argument 'request'` but the CSRF is still not being exempted. I still got `{"detail": "CSRF check Failed"}`. I think this is related to https://github.com/vitalik/django-ninja/issues/1068 🤔 

Thank you very much for helping me out ❤️

**Comment by eadwinCode** [comment]
Ummmh... Can you show me how you are making the request?

**Comment by Tragio** [comment]
@eadwinCode do you have discord or something? Maybe it will be easier to chat and then share here the results 🤔

**Comment by eadwinCode** [comment]
Oh okay I don't have discord
