### ISSUE TITLE
Incompatible with Django Ninja 1.2.0

### ISSUE THREAD

**Issue by shmulvad** [eadwinCode/django-ninja-extra#148]
Recently, version 1.2.0 of Django Ninja was released. This package should be updated to support that new version. 

## Reproducing the Error

Add the following to a `requirements.txt` file:

```
django-ninja==1.2.0
django-ninja-extra==0.20.7
```

Run `uv pip install -r requirements.txt`. The following error should occur:

```
× No solution found when resolving dependencies:
╰─▶ Because django-ninja-extra==0.20.7 depends on django-ninja==1.1.0 and you require
    django-ninja-extra==0.20.7, we can conclude that you require django-ninja==1.1.0.
    And because you require django-ninja==1.2.0, we can conclude that the requirements are
    unsatisfiable.
```

Which is due to this project pinning `django-ninja` to a specific version in the `pyproject.toml`:

https://github.com/eadwinCode/django-ninja-extra/blob/30066d59b82d1047c846cde5ee5f3c67d9d4bfeb/pyproject.toml#L43-L49

## Suggested Resolution

Update the `pyproject.toml` from `"django-ninja==1.1.0"` to `"django-ninja>=1.1.0"` or even `"django-ninja>=1.2.0"`.

**Comment by eadwinCode** [comment]
@shmulvad your suggestion will be done on the next release. There are some updates from django-ninja that needs to be supported in django-ninja-extra.

**Comment by shmulvad** [comment]
Seems like this is fixed now.
