### ISSUE TITLE
Generated operationId can start with number breaking many openapi generators

### ISSUE THREAD

**Issue by Loeffeldude** [eadwinCode/django-ninja-extra#173]
When not providing an operationId a random UUID is generated and cut off. 

https://github.com/eadwinCode/django-ninja-extra/blob/f12eaeb1298524b72c7253762618a851485cb2b9/ninja_extra/controllers/base.py#L450-L453

This UUID can beginn with a number which is not an valid type name in, for instance typescript type or a valid method name in PHP.

It would be ideal to guarantee that the randomly generated string starts with a letter.

**Comment by eadwinCode** [comment]
@Loeffeldude will fix this shortly
