### ISSUE TITLE
Inconsistent and Inflexible Exception Handling

### ISSUE THREAD

**Issue by tareksanger** [eadwinCode/django-ninja-extra#184]
The current implementation of exception handling in Django Ninja Extra, specifically in the `NinjaExtraAPI` class, presents several issues that make it difficult to customize error responses and maintain consistent error formatting across an application.

Key problems:

1. Hardcoded Error Format:
   The `api_exception_handler` method in `NinjaExtraAPI` hardcodes the error response format to `{"detail": exc.detail}`. This makes it impossible to use custom error schemas without overriding core functionality.

2. Lack of Extensibility:
   The exception handling is tightly coupled with the API class, making it challenging to extend or modify the error handling behavior without subclassing and overriding multiple methods.

3. Inconsistent Error Responses:
   Different types of exceptions (e.g., validation errors, HTTP errors, API exceptions) may result in inconsistent error formats, complicating error handling on the client side.

4. Difficulty in Adding Custom Fields:
   Adding custom fields to error responses (such as error codes, request IDs, or timestamps) requires significant modifications to the core API class.

5. Limited Control Over HTTP Headers:
   The current implementation only allows setting the "Retry-After" header for throttled requests, limiting the ability to include custom headers in error responses.

Proposed Solution:

1. Introduce a customizable error response schema that can be set at the API level.
2. Implement a more flexible exception handling mechanism that allows for easy customization of error responses for different exception types.
3. Provide hooks or middleware for modifying error responses without requiring subclassing of the main API class.
4. Ensure consistent error formatting across all types of exceptions.
5. Allow for easy addition of custom fields and headers to error responses.

These changes would significantly improve the flexibility and consistency of error handling in Django Ninja Extra, making it easier for developers to implement custom error handling logic and maintain a consistent API contract.

**Comment by eadwinCode** [comment]
@tareksanger I am some how confused when you say `API` class... Are you referring to `APIException` class or `NinjaExtraAPI` class ?

**Comment by eadwinCode** [comment]
NinjaExtra only extends exception handling capabilities of Django Ninja and you can still extend it further to customize your custom exceptions. See [here](https://django-ninja.dev/guides/errors/) for more context.

Also, your PRs are very welcomed for changes you wanna see in the project.

**Comment by tareksanger** [comment]
> @tareksanger I am some how confused when you say `API` class... Are you referring to `APIException` class or `NinjaExtraAPI` class ?

I'm referring to the `NinjaExtraAPI` Class.

> NinjaExtra only extends exception handling capabilities of Django Ninja and you can still extend it further to customize your custom exceptions. See [here](https://django-ninja.dev/guides/errors/) for more context.
> 
> Also, your PRs are very welcomed for changes you wanna see in the project.

``` python
class ErrorCode(enum.Enum):
    ....

class ErrorSchema(Schema):
    code: ErrorCode = Field(default=ErrorCode.UNKNOWN)
    uuid: Optional[str] = Field(default_factory=lambda: uuid4())
    error: Primitive | dict | list

def create_error_response(request: HttpRequest, error: Union[str, Dict[str, Any], list], status: int) -> HttpResponse:
    print(error)
    error_schema = ErrorSchema.from_error(_(error) if isinstance(error, str) else error)
    return api.create_response(request, error_schema.dict(), status=status)


@api.exception_handler(HttpError)
def handle_http_error(request: HttpRequest, exc: HttpError) -> HttpResponse:
    return create_error_response(request, exc.message, exc.status_code)

```

The above does absolutely nothing my responses all come through as `{"detail": "Some Error Message"}`, and I believe its due to the following inside the DjangoNinjaExtra class.

``` python
    def api_exception_handler(
        self, request: HttpRequest, exc: exceptions.APIException
    ) -> HttpResponse:
        headers: Dict = {}
        if isinstance(exc, exceptions.Throttled):
            headers["Retry-After"] = "%d" % float(exc.wait or 0.0)

        if isinstance(exc.detail, (list, dict)):
            data = exc.detail
        else:
            data = {"detail": exc.detail}

        response = self.create_response(request, data, status=exc.status_code)
        for k, v in headers.items():
            response.setdefault(k, v)

        return response
        
   ```

**Comment by tareksanger** [comment]
The issue was with
