### ISSUE TITLE
async session auth bug

### ISSUE THREAD

**Issue by amirreza8002** [eadwinCode/django-ninja-extra#201]
hi
[this lookup](https://github.com/eadwinCode/django-ninja-extra/blob/master/ninja_extra/security/session.py#L19-L20) is gonna error
django can't call sync database calls in async env

```py
user = await request.auser()
if user.is_authenticated:
    ...
```

this should work

**Comment by eadwinCode** [comment]
@amirreza8002 Oh that's a bug, thanks. Will fix that shortly

**Comment by eadwinCode** [comment]
@amirreza8002 can you test with the lastest release?

**Comment by eadwinCode** [comment]
@amirreza8002, first of all, Ninja-Extra supports difference versions of Django, and `auser` was added from [Django 5.0](https://github.com/django/django/commit/e846c5e7246a0ffbe5dcf07a2b6c7c2a47537eb3). 
Secondly, the question was if the recent release unblocks you.
Thirdly, if you think something is not properly done in the project, this is an open source project, you are always free to made changes to it and create a PR.
Lastly, thanks for your feedback, those changes will available on future release.

**Comment by amirreza8002** [comment]
hi
if my message sounded hostile i apologize, it was not meant to be that way

i am not using this project atm 
it just seemed interesting so i took a look, and since i have been bitten by the problem i mentioned, thought I'd make an issue

**Comment by eadwinCode** [comment]
@amirreza8002 Alright that's fine
