### ISSUE TITLE
How do I override the default methods for the ModelControllerBase operations?

### ISSUE THREAD

**Issue by josefson** [eadwinCode/django-ninja-extra#207]
Given the following code I would like to setup my own create/update methods without having to write a child uri to  the api_controller.
```
@api_controller("/fisica", tags=["PessoaFisica"])
class PessoaFisicaController(ModelControllerBase):
    model_config = ModelConfig(
        model=PessoaFisica,
        schema_config=ModelSchemaConfig(depth=1),
        allowed_routes=["find_one", "list", "delete", "update"],
    )
```
Right now i've got the bellow which only runs if the first argument of @route.put has something like "put/{pessoa_id}", then the code bellow is executed, otherwise if i leave "{pessoa_id}" I think it goes to the superclass method's i want to avoid.

How do i override this?

```
    @route.put("{pessoa_id}", response={200: PessoaFisicaSchemaCreate}, summary="Update an item", description="Update PessoaFisica by id")
    def update(self, pessoa: int, payload: PessoaFisicaSchemaCreate):
        __import__('ipdb').set_trace()
```

**Comment by eadwinCode** [comment]
In the allowed_routes remove `update`

**Comment by josefson** [comment]
> In the `allowed_routes` remove `update`


I've done that and i get Method not allowed.

**Comment by eadwinCode** [comment]
@josefson I understand now, the `find` creates a route  [GET]`/{int: id}` and you are making another one [PUT]`{pessoa_id}`. Both paths are similar and the `find` will be resolved first when you make a `PUT` request, resulting in `Method not allowed`. If you check the API docs you will understand better.

The only way to solve this is to have the `find` and `update` use the same path parameter, that way, their operations will be merged. Another way is to have a different route completely like your solution `"put/{pessoa_id}"` or `"{pessoa_id}/update"`

```python
    @route.put("/{str:id}", response={200: PessoaFisicaSchemaCreate}, summary="Update an item", description="Update PessoaFisica by id")
    def update(self, id: int, payload: PessoaFisicaSchemaCreate):
        __import__('ipdb').set_trace()
```

**Comment by josefson** [comment]
I tried the bellow and still get method not allowed. Even if i remove the "find" from allowed_routes I still get method not allowed.
The other option works, but it kind of breaks api standard across the project where a lot of non relational Models just works without the sufix/prefix apis, just by the http method.
Right now all I can use is the Controller Base and class usage =/, which is already good class encapsulation but It would be better if We could use the ModelControllerBase, and override using the http methods.
```
@route.put("/{str:id}", response={200: PessoaFisicaSchemaCreate}, summary="Update an item", description="Update PessoaFisica by id")
    def update(self, id: int, payload: PessoaFisicaSchemaCreate):
        __import__('ipdb').set_trace()
```

**Comment by josefson** [comment]
Thanks!! That solved it!
