### ISSUE TITLE
HELP! Custom error response schema for all exception within api.

### ISSUE THREAD

**Issue by uzza1hossain** [eadwinCode/django-ninja-extra#208]
At this moment api return error as `{'detail': 'Error Message'}` 
but there is also pydantic errors like `{'type': 'missing', 'loc': ('body', 'data', 'password'), 'msg': 'Field required'}`

I want all errors should follow a specific format
`{'success': 'false', 'message': 'Human friendly message'}`

How can I achieve this?

**Comment by Neon-jeff** [comment]
How did yo u achieve this, I am trying to customize the exception class thrown from JWTAuth() in ninja-jwt
