### ISSUE TITLE
Incomplete async support: sync_to_async usage in ModelService

### ISSUE THREAD

**Issue by CMarcher-Ahuora** [eadwinCode/django-ninja-extra#215]
Within the `ModelService` class, the "asynchronous" object operations appear to just use the `sync_to_async` wrapper function provided by Django, while ultimately calling a synchronous Django ORM function.

For example, the `get_one_async` function calls `get_one` with `sync_to_async`:

```python
    async def get_one_async(self, pk: t.Any, **kwargs: t.Any) -> t.Any:
        return await sync_to_async(self.get_one, thread_sensitive=True)(pk, **kwargs)
```

And `get_one` calls a synchronous in-built Django function `get_object_or_exception`.

```python
   def get_one(self, pk: t.Any, **kwargs: t.Any) -> t.Any:
        obj = get_object_or_exception(
            klass=self.model, error_message=None, exception=NotFound, pk=pk
        )
        return obj
```

Asynchronous versions of many of these ORM functions, such as `get_object_or_exception` are [available](https://docs.djangoproject.com/en/5.1/topics/http/shortcuts/#get-object-or-404) (`aget_object_or_404`). Another resource showing async used within core Django features: [async queries](https://docs.djangoproject.com/en/5.1/topics/db/queries/#async-queries). Where possible, current use of synchronous ORM functions should be converted to their younger asynchronous counterparts, allowing django-ninja-extra to have proper async support.

**Comment by eadwinCode** [comment]
@CMarcher-Ahuora this was an oversight. And thanks for the suggestion. Will look into this soon

**Comment by CMarcher-Ahuora** [comment]
To be fair to you, I have only just learned that all async Django ORM functions are just wrappers for `sync_to_async` as well, so I'm not sure whether it would be worth going through the effort of using these "async" versions.
