### ISSUE TITLE
How to Implement Testcase with NINJA JWT Authentication ?

### ISSUE THREAD

**Issue by recervictory** [eadwinCode/django-ninja-extra#22]
I have implemented Ninja JWT Authentication with Ninja Extra.

```
@api_controller("post/", tags=["Post"])
class PostController:
        @route.post("", response=PostOut, auth=JWTAuth())
         def create_post(self, payload: PostIn):
                post = Post.Object.Create(**payload.dict())
                resturn post
```

I want to implement `TestPostController` But how I apply NINJA JWT with that?

**Comment by recervictory** [comment]
I am totally new to Django, I am not able to implement that. I want to add `headers={'HTTP_AUTHORIZATION': 'Bearer' +self.access_token }` in the response post method but is showing `Unauthorized`. My code like this...

`response= self.client.post("", jsoon=dict(description="Sample Post", ....)`

**Comment by FabianClemenz** [comment]
@recervictory i posted my example of how i test the APIs with Ninja JWT in the issue too - maybe this helps :)

https://github.com/eadwinCode/django-ninja-extra/issues/3#issuecomment-1473551557
