### ISSUE TITLE
Unnecessary request information sent to console and logs

### ISSUE THREAD

**Issue by horkong** [eadwinCode/django-ninja-extra#24]
Regarding the following commit: 8ff831e1a9b99ce1f43b5dd96b8ed878be41787b

The change has led to unnecessary logs. With Django's mail_admins() enabled, it causes double the emails sent, and even sends an email for every 4xx error.

Console:
![image](https://user-images.githubusercontent.com/29617606/181606884-7830c029-b58a-4e3b-a183-0e587b0b46b9.png)

Email received (empty traceback):
![image](https://user-images.githubusercontent.com/29617606/181607027-6c5c5953-753a-4a82-a261-09401663c5b2.png)

**Comment by eadwinCode** [comment]
@horkong I will look into it

**Comment by eadwinCode** [comment]
@horkong fix will be available on next release

**Comment by eadwinCode** [comment]
@horkong check: https://github.com/eadwinCode/django-ninja-extra/releases/tag/0.15.6
thanks
