### ISSUE TITLE
Injector library is outdate

### ISSUE THREAD

**Issue by corvis** [eadwinCode/django-ninja-extra#47]
First of all thank you for the great library. I noticed it has `injector == 0.19.0` as a dependency but at the moment the latest version of injector is `0.20.1` so installing `django-ninja-extra` forces us to downgrade injector.

I'm wondering if there is any reason to keep specific version in dependencies rather then something like `injector >= 0.19.0` maybe there are some known compatibility issues?

**Comment by eadwinCode** [comment]
Thanks, @corvis. injector v0.20.1 dropped support for py3.6 and there were some compatibility issues. I think that's why I left it at 0.19.0. but I will look into it this weekend.

**Comment by eadwinCode** [comment]
@corvis I believe I can close this yeah?

**Comment by corvis** [comment]
Yep, many thanks!

**Comment by eadwinCode** [comment]
You 're welcome
