### ISSUE TITLE
Documentation: Add Example App

### ISSUE THREAD

**Issue by mister-rao** [eadwinCode/django-ninja-extra#49]
Can we have an example app that uses Controllers, Permissions, Services, Modules and dependency injection?

**Comment by matthias-hiemer** [comment]
Absolutely +1 
Topic for me wouldn't be important. Do DRF or Ninja already have an example that would be easy to fork?

**Comment by eadwinCode** [comment]
I don't know. Maybe you can check and see if there are any.

**Comment by matthias-hiemer** [comment]
I found this existing one from you https://github.com/eadwinCode/bookstoreapi which is fine for me. Would it make sense to take this one and update it to the current version?

**Comment by eadwinCode** [comment]
Yes. The current version works fine on it
