### ISSUE TITLE
Is there a way to redirect to an external site?

### ISSUE THREAD

**Issue by yamaday-isid** [eadwinCode/django-ninja-extra#55]
Thank you for developing this great project!

We are currently using django-nina-extra to develop our application.
We are facing a use case where we need to redirect responses to an external site.

The API we are developing is implemented in a class that inherits from ControllerBase and is given the `api_controller` decorator.

```py
from django.shortcuts import redirect

@api_controller('sample/')
class UsersController(ControllerBase):
    @route.get('', response={302: None})
    def get_users(self):
        # not working
        return redirect("https://sample.some-page")
```

Is there a way to redirect to an external site?

## Related issue

https://github.com/vitalik/django-ninja/issues/224

**Comment by eadwinCode** [comment]
@yamaday-isid Yes, this is should fine but I will take a look at it.

**Comment by eadwinCode** [comment]
I have looked at this and it works fine on my end. @yamaday-isid can you show me what error you were getting?

**Comment by yamaday-isid** [comment]
@eadwinCode Thank you for checking. 
And I am really sorry. It seems I was wrong.

---

I will share the version of the library and context we were using.

the version of the library:

- django-ninja-extra 0.15.4

context:

We were calling our developed API endpoints from OpenAPI docs generated by django-ninja-extra (or django-ninja).  - http://127.0.0.1:8000/api/docs 

And I was encountering the following error.

![image](https://user-images.githubusercontent.com/86820659/224459661-754b40be-d529-4579-a313-5a8796983ea9.png)

We noticed that this is the correct behavior in situations where we redirect to an external site.
Django-ninaja-extra  works fine.

I am really sorry.
This issue can be closed.

**Comment by eadwinCode** [comment]
Yes, In Swagger thats the behaviour when you return a redirect response. @yamaday-isid Thanks for clearing this out.
