### ISSUE TITLE
[documentation] controller permission typo

### ISSUE THREAD

**Issue by lewoudar** [eadwinCode/django-ninja-extra#56]
Hi folks,
when reading this [section](https://eadwincode.github.io/django-ninja-extra/api_controller/api_controller_permission/) of the documentation, I saw a typo on the last line.
Instead of `~ (not) eg: !(permissions.IsAuthenticated & ReadOnly)`, I think it should be `~ (not) eg: ~(permissions.IsAuthenticated & ReadOnly)`

**Comment by eadwinCode** [comment]
@lewoudar Thanks for spotting this error. It will be rectified shortly.

**Comment by eadwinCode** [comment]
Resolved

**Comment by lewoudar** [comment]
Thanks! But it seems like rtd is not updated
