### ISSUE TITLE
Optional Auth

### ISSUE THREAD

**Issue by baseplate-admin** [eadwinCode/django-ninja-extra#60]
Hi there,

Thanks for creating this library. I was thinking if it was possible to add optional auth

---

For some more context see https://github.com/vitalik/django-ninja/discussions/709

**Comment by eadwinCode** [comment]
Hi @baseplate-admin,
This project depends on Django `Ninja`. Once the feature is working in Django ninja, it will definitely work here.

But I think the example @vitalik shared is a great fix for this problem.

**Comment by baseplate-admin** [comment]
Hmm the problem is if i dont pass a value in the Aurhorization header, it will throw error. So if i have no Authorization value it doesnt work.

Sorry for pinging here.

**Comment by eadwinCode** [comment]
oh oaky. I think I understand the problem now. You need a custom `HTTPAuthBase` implementation

**Comment by eadwinCode** [comment]
```python
class CustomHttpAuthBase(HttpAuthBase, ABC):
    openapi_scheme: str = "bearer"
    header: str = "Authorization"

    def __call__(self, request: HttpRequest) -> Optional[Any]:
        headers = get_headers(request)
        auth_value = headers.get(self.header)
        if not auth_value:
             return AnonymousUser() # if there is no key, we return AnonymousUser object
        parts = auth_value.split(" ")

        if parts[0].lower() != self.openapi_scheme:
            if settings.DEBUG:
                logger.error(f"Unexpected auth - '{auth_value}'")
            return None
        token = " ".join(parts[1:])
        return self.authenticate(request, token)

    @abstractmethod
    def authenticate(self, request: HttpRequest, token: str) -> Optional[Any]:
        pass  # pragma: no cover
```
Then you can extend this for any authentication type you want.
```python
class AuthBearer(CustomHttpAuthBase):
    def authenticate(self, request, token):
        if token == "supersecret":
            return AuthenticatedUser()
        else:
            return AnonymousUser()
```

@baseplate-admin, Let me know if this works for you.

**Comment by baseplate-admin** [comment]
You are pretty close to what i wanted. Is it possible to add this to `ninja-extra`? ( i cant be the only person who requires this 👀)

**Comment by baseplate-admin** [comment]
Consequently are you willing to merge some of the codes into the `django-ninja` codebase ?

**Comment by baseplate-admin** [comment]
Hi it works as expected. Thanks for looking into it. :D

**Comment by eadwinCode** [comment]
> You are pretty close to what i wanted. Is it possible to add this to `ninja-extra`? ( i cant be the only person who requires this 👀)

There is some changes coming up on auth usage for Django ninja... I think this will be factored in by that time.
