### ISSUE TITLE
Remove `default_app_config`

### ISSUE THREAD

**Issue by nbhargava** [eadwinCode/django-ninja-extra#7]
`default_app_config` is now deprecated and will be removed. If it's important to preserve this for backwards compatibility, taking an approach like waffle may make sense: https://github.com/django-waffle/django-waffle/blob/95dc760fd6b0a7e2769a991641c7213c05b0073d/waffle/__init__.py#L10

Warning for reference:
```
RemovedInDjango41Warning: 'ninja_extra' defines default_app_config = 'ninja_extra.apps.NinjaExtraConfig'. Django now detects this configuration automatically. You can remove default_app_config.
    app_config = AppConfig.create(entry)
```

**Comment by eadwinCode** [comment]
@nbhargava Thanks. I will look into it
