### ISSUE TITLE
Mistake in documentation?

### ISSUE THREAD

**Issue by don-philipe** [eadwinCode/django-ninja-extra#70]
Hello,

I tried to get access to the request attribute as it is done in the documentation here: https://eadwincode.github.io/django-ninja-extra/tutorial/authentication/ (`self.request`) but I failed. After a little debugging, I found out that I can access via `self.context.request`.

I guess that the documentation is not correct at this point? I can provide a PR if that the case. Or am I having just some weird circumstances, so that thing act different for me? I would be happy to have that cleared before taking further actions.

**Comment by eadwinCode** [comment]
Thanks for fixing this
