### ISSUE TITLE
[BUG] RouteContext (Async): 'NoneType' object has no attribute 'request'

### ISSUE THREAD

**Issue by joaoflaviosantos** [eadwinCode/django-ninja-extra#75]
Hello @eadwinCode,

I've encountered an issue related to the usage of "self.context.request.user" within asynchronous routes. I'd like to point out that this problem seems to arise exclusively when utilizing Uvicorn, especially in scenarios where multiple requests are simultaneously made to different routes.

The error log provided below outlines the situation:

```log
"GET - AppController[retorna_detalhes] /api/inteli/120e39ad-6cd4-4d7c-812d-e4288a724d1f" 0.033296823501586914
"GET - AppController[listar] /api/inteli/teste/120e39ad-6cd4-4d7c-812d-e4288a724d1f/embalagens" ("'NoneType' object has no attribute 'request'",)
'NoneType' object has no attribute 'request'
Traceback (most recent call last):
  File "C:\Users\dev\Desktop\project\backend\venv\lib\site-packages\ninja_extra\operation.py", line 400, in run
    result = await self.view_func(request, **values)
  File "C:\Users\dev\Desktop\project\backend\venv\lib\site-packages\ninja_extra\controllers\route\route_functions.py", line 178, in as_view
    result = await self.route.view_func(
  File ".\apps\setores\inteli\controllers.py", line 256, in listar_embalagens
    request_context_content = self.context.request,
AttributeError: 'NoneType' object has no attribute 'request'
```

It appears that the issue lies within the generation of the request context (RouterContext) by `django_ninja_extra`. Strangely, it appears that the context is only being generated for the first incoming request (almost at random).

Upon reviewing the code, it seems the problem might be located in line 19 of the "backend\venv\Lib\site-packages\ninja_extra\modules.py" file:

```python
@receiver([route_context_started, route_context_finished], sender=RouteContext)
def route_context_handler(
    *args: Any, route_context: Optional[RouteContext] = None, **kwargs: Any
) -> None:
    app = cast(Any, apps.get_app_config("ninja_extra"))
    app.ninja_extra_module.set_route_context(route_context) # <-- The error seems to be originating here
```

Versions:

- python: [3.8.6]
- django: [4.1.7]
- django-Ninja: [0.22.2]
- django-ninja-extra [0.19.1]
- django-ninja-jwt [5.2.5]

To provide some context, I am running the application using the following command:

```shell
uvicorn core.asgi:application --host 192.168.1.79 --workers 4 --port 8000 --reload
```

Thank you once again for your assistance, and I would like to extend my congratulations on the exceptional work you've done with [Django Ninja Extra](https://github.com/eadwinCode/django-ninja-extra)!

Best regards,
João Flávio

**Comment by joaoflaviosantos** [comment]
Hello again @eadwinCode,

I wanted to share an update on the situation. I've made a change to the "backend\venv\Lib\site-packages\ninja_extra\modules.py" file that seems to have resolved the issue:

```python
@receiver([route_context_started, route_context_finished], sender=RouteContext)
def route_context_handler(
    *args: Any, route_context: Optional[RouteContext] = None, **kwargs: Any
) -> None:
    app = cast(Any, apps.get_app_config("ninja_extra"))
    if route_context is not None:
        app.ninja_extra_module.set_route_context(route_context)
```

I wanted to explain the rationale behind this adjustment. It essentially involves setting the new "self._local.route_context" of the "NinjaExtraModule" class using the "ninja_extra_module.set_route_context()" method, but only if the current "route_context" is not None.

Remarkably, this modification seems to have successfully resolved the 'NoneType' object attribute error that was cropping up while using Uvicorn with 4 workers and asynchronous routes.

Your insights and guidance throughout this process have been invaluable. 

Thank you for your support!

Best regards,
João Flávio

**Comment by eadwinCode** [comment]
> Hello @eadwinCode,
> 
> I've encountered an issue related to the usage of "self.context.request.user" within asynchronous routes. I'd like to point out that this problem seems to arise exclusively when utilizing Uvicorn, especially in scenarios where multiple requests are simultaneously made to different routes.
> 
> The error log provided below outlines the situation:
> 
> ```
> "GET - AppController[retorna_detalhes] /api/inteli/120e39ad-6cd4-4d7c-812d-e4288a724d1f" 0.033296823501586914
> "GET - AppController[listar] /api/inteli/teste/120e39ad-6cd4-4d7c-812d-e4288a724d1f/embalagens" ("'NoneType' object has no attribute 'request'",)
> 'NoneType' object has no attribute 'request'
> Traceback (most recent call last):
>   File "C:\Users\dev\Desktop\project\backend\venv\lib\site-packages\ninja_extra\operation.py", line 400, in run
>     result = await self.view_func(request, **values)
>   File "C:\Users\dev\Desktop\project\backend\venv\lib\site-packages\ninja_extra\controllers\route\route_functions.py", line 178, in as_view
>     result = await self.route.view_func(
>   File ".\apps\setores\inteli\controllers.py", line 256, in listar_embalagens
>     request_context_content = self.context.request,
> AttributeError: 'NoneType' object has no attribute 'request'
> ```
> 
> It appears that the issue lies within the generation of the request context (RouterContext) by `django_ninja_extra`. Strangely, it appears that the context is only being generated for the first incoming request (almost at random).
> 
> Upon reviewing the code, it seems the problem might be located in line 19 of the "backend\venv\Lib\site-packages\ninja_extra\modules.py" file:
> 
> ```python
> @receiver([route_context_started, route_context_finished], sender=RouteContext)
> def route_context_handler(
>     *args: Any, route_context: Optional[RouteContext] = None, **kwargs: Any
> ) -> None:
>     app = cast(Any, apps.get_app_config("ninja_extra"))
>     app.ninja_extra_module.set_route_context(route_context) # <-- The error seems to be originating here
> ```
> 
> Versions:
> 
> * python: [3.8.6]
> * django: [4.1.7]
> * django-Ninja: [0.22.2]
> * django-ninja-extra [0.19.1]
> * django-ninja-jwt [5.2.5]
> 
> To provide some context, I am running the application using the following command:
> 
> ```shell
> uvicorn core.asgi:application --host 192.168.1.79 --workers 4 --port 8000 --reload
> ```
> 
> Thank you once again for your assistance, and I would like to extend my congratulations on the exceptional work you've done with [Django Ninja Extra](https://github.com/eadwinCode/django-ninja-extra)!
> 
> Best regards, João Flávio

Hi @joaoflaviosantos Thanks for thoroughly debugging this. I will look into it and get back to you with a solution.

**Comment by eadwinCode** [comment]
> Hello again @eadwinCode,
> 
> I wanted to share an update on the situation. I've made a change to the "backend\venv\Lib\site-packages\ninja_extra\modules.py" file that seems to have resolved the issue:
> 
> ```python
> @receiver([route_context_started, route_context_finished], sender=RouteContext)
> def route_context_handler(
>     *args: Any, route_context: Optional[RouteContext] = None, **kwargs: Any
> ) -> None:
>     app = cast(Any, apps.get_app_config("ninja_extra"))
>     if route_context is not None:
>         app.ninja_extra_module.set_route_context(route_context)
> ```
> 
> I wanted to explain the rationale behind this adjustment. It essentially involves setting the new "self._local.route_context" of the "NinjaExtraModule" class using the "ninja_extra_module.set_route_context()" method, but only if the current "route_context" is not None.
> 
> Remarkably, this modification seems to have successfully resolved the 'NoneType' object attribute error that was cropping up while using Uvicorn with 4 workers and asynchronous routes.
> 
> **Does this adjustment seem right to you?**
> 
> Thank you for your support!
> 
> Best regards, João Flávio

If this works for you now, then it's okay for you to keep it. But I still need to look into using it to see if there are other solutions.

**Comment by joaoflaviosantos** [comment]
Thank you for the return @eadwinCode!

I'll perform the test and commit the change later for your assessment.

**Comment by joaoflaviosantos** [comment]
Hello again @eadwinCode,

I also performed tests without the adjustment flagged above. 

However, I did not understand if the error returned in the route in the file "teststest_async_auth.py", was already expected or was not covered by the unit tests:

```log
tests\test_async_auth.py ....."GET - demo_operation /django_auth" 0.0009965896606445312
.."GET - demo_operation /callable?auth=demo"
.."GET - demo_operation /apikeyquery?key=keyquerysecret" 
.."GET - demo_operation /apikeyheader" 
.."GET - demo_operation /apikeycookie" 
.."GET - demo_operation /basic" 0.0010063648223876953
."GET - demo_operation /basic" 0.0010159015655517578
.Invalid Authorization header
Traceback (most recent call last):
  File "C:\Users\joaof\Documents\django-ninja-extra\venv\lib\site-packages\ninja\security\http.py", line 84, in decode_authorization
    username, password = b64decode(user_pass_encoded).decode().split(":", 1)
  File "c:\users\joaof\appdata\local\programs\python\python38\lib\base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\joaof\Documents\django-ninja-extra\ninja_extra\security\http.py", line 40, in __call__
    username, password = self.decode_authorization(auth_value)
  File "C:\Users\joaof\Documents\django-ninja-extra\venv\lib\site-packages\ninja\security\http.py", line 89, in decode_authorization
    raise DecodeError("Invalid Authorization header") from e
ninja.security.http.DecodeError: Invalid Authorization header
.Invalid Authorization header
Traceback (most recent call last):
  File "C:\Users\joaof\Documents\django-ninja-extra\ninja_extra\security\http.py", line 40, in __call__
    username, password = self.decode_authorization(auth_value)
  File "C:\Users\joaof\Documents\django-ninja-extra\venv\lib\site-packages\ninja\security\http.py", line 81, in decode_authorization
    raise DecodeError("Invalid Authorization header")
ninja.security.http.DecodeError: Invalid Authorization header
.."GET - demo_operation /bearer" 0.0009946823120117188
.Unexpected auth - 'Invalid bearertoken'
```

Apparently the problem is related to the "django-ninja" security module. 

Do you think this might be related to the problem I've been experiencing with asynchronous routes?

**Comment by eadwinCode** [comment]
> Hello again @eadwinCode,
> 
> I also performed tests without the adjustment flagged above.
> 
> However, I did not understand if the error returned in the route in the file "teststest_async_auth.py", was already expected or was not covered by the unit tests:
> 
> ```
> tests\test_async_auth.py ....."GET - demo_operation /django_auth" 0.0009965896606445312
> .."GET - demo_operation /callable?auth=demo"
> .."GET - demo_operation /apikeyquery?key=keyquerysecret" 
> .."GET - demo_operation /apikeyheader" 
> .."GET - demo_operation /apikeycookie" 
> .."GET - demo_operation /basic" 0.0010063648223876953
> ."GET - demo_operation /basic" 0.0010159015655517578
> .Invalid Authorization header
> Traceback (most recent call last):
>   File "C:\Users\joaof\Documents\django-ninja-extra\venv\lib\site-packages\ninja\security\http.py", line 84, in decode_authorization
>     username, password = b64decode(user_pass_encoded).decode().split(":", 1)
>   File "c:\users\joaof\appdata\local\programs\python\python38\lib\base64.py", line 87, in b64decode
>     return binascii.a2b_base64(s)
> binascii.Error: Incorrect padding
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "C:\Users\joaof\Documents\django-ninja-extra\ninja_extra\security\http.py", line 40, in __call__
>     username, password = self.decode_authorization(auth_value)
>   File "C:\Users\joaof\Documents\django-ninja-extra\venv\lib\site-packages\ninja\security\http.py", line 89, in decode_authorization
>     raise DecodeError("Invalid Authorization header") from e
> ninja.security.http.DecodeError: Invalid Authorization header
> .Invalid Authorization header
> Traceback (most recent call last):
>   File "C:\Users\joaof\Documents\django-ninja-extra\ninja_extra\security\http.py", line 40, in __call__
>     username, password = self.decode_authorization(auth_value)
>   File "C:\Users\joaof\Documents\django-ninja-extra\venv\lib\site-packages\ninja\security\http.py", line 81, in decode_authorization
>     raise DecodeError("Invalid Authorization header")
> ninja.security.http.DecodeError: Invalid Authorization header
> .."GET - demo_operation /bearer" 0.0009946823120117188
> .Unexpected auth - 'Invalid bearertoken'
> ```
> 
> Apparently the problem is related to the "django-ninja" security module.
> 
> Do you think this might be related to the problem I've been experiencing with asynchronous routes?

@joaoflaviosantos Maybe you can create a PR, lets look at the test together

**Comment by eadwinCode** [comment]
@joaoflaviosantos Can you check if the #78 works for you

**Comment by eadwinCode** [comment]
@joaoflaviosantos lets forget about the test for now. We can fix that later. 
```shell
uvicorn core.asgi:application --host 192.168.1.79 --workers 4 --port 8000 --reload
```
Were you able to test with the command above to see if the initial problem has been resolved?

**Comment by joaoflaviosantos** [comment]
Hello again @eadwinCode.

I performed several tests here with the adjustments made in PR #78 and the problem regarding RouteContext (Async) did not occur again. 

Apparently, it is only necessary to adjust the unit tests, as you mentioned earlier. 

I will be using PR version #78 in my development environment. If I detect something strange I'll signal you again. 

Let me know if you need help with unit testing. 

Again, thank you so much for your help!

**Comment by joaoflaviosantos** [comment]
> @joaoflaviosantos That is some good news 😎. I will look into the test and fix that. Thanks

Thank you very much for adjusting @eadwinCode!
