### ISSUE TITLE
[FEATURE] Add HEAD and OPTIONS in @http_generic 

### ISSUE THREAD

**Issue by facundopadilla** [eadwinCode/django-ninja-extra#9]
Hello everyone, I had a problem creating a generic endpoint (as there is no OPTIONS and HEAD method). I had to add them in the package code.

![image](https://user-images.githubusercontent.com/64610246/154816746-1a9e6e9c-699c-4209-9c59-ea48e4d219f4.png)

```python
# route/__init__.py
...
methods = list(map(lambda m: m.upper(), methods))
not_valid_methods = list(set(methods) - set(ROUTE_METHODS))  # ROUTE_METHODS doesn't have "OPTIONS" and "HEAD"
if not_valid_methods:
raise RouteInvalidParameterException(
           f"Method {','.join(not_valid_methods)} not allowed"
    )
...
```

**Comment by eadwinCode** [comment]
@facundopadilla Thanks for pointing this out. I will be fixed as soon as possible

**Comment by eadwinCode** [comment]
@facundopadilla you need to upgrade to the latest version of the library. That has already been added already

**Comment by facundopadilla** [comment]
> @facundopadilla you need to upgrade to the latest version of the library. That has already been added already

Thanks you! Now works! :D
