### ISSUE TITLE
Throttling before authentication

### ISSUE THREAD

**Issue by MGotkowski** [eadwinCode/django-ninja-extra#91]
It looks like right now the throttling is run after the authentication. When using BasiAuth it's possible to brute force an endpoint and the user won't be throttled because it won't pass the authentication. I think that throttling should be run before auth. 
Is there a way to do that with current code?

```python
@api_controller(
    "users",
    tags=["Users"],
    auth=LoginAuthentication(), # this is custom BasicAuth
    permissions=[],
)
class UserController(ControllerBase):
    throttling_classes = [AnonRateThrottle, UserRateThrottle]
    
    @http_get("/", response=List[UserSchema])
    def get_users(self, request):
        """
        List descendant users
        """
        user = request.auth
        return user.get_descendants(include_self=True)
```

**Comment by eadwinCode** [comment]
@MGotkowski if throttling runs before authentication, `UserRateThrottle` will be insignificant. Because the UserRateThrottle requires `request.user.id` to create a throttling cache key

**Comment by eadwinCode** [comment]
But I understand the challenge here. I will look into it how it can be solved

**Comment by MGotkowski** [comment]
I found that with this settings
```python
class UserController(ControllerBase):
    throttling_classes = [AnonRateThrottle, UserRateThrottle]
```
`AnonRateThrottle` is also used when the user is authenticated. So if it has lower rate than `UserRateThrottle` the requests will be throttled using that rate not the one for authenticated users.

**Comment by eadwinCode** [comment]
> I found that with this settings
> 
> ```python
> class UserController(ControllerBase):
>     throttling_classes = [AnonRateThrottle, UserRateThrottle]
> ```
> 
> `AnonRateThrottle` is also used when the user is authenticated. So if it has lower rate than `UserRateThrottle` the requests will be throttled using that rate not the one for authenticated users.

Yeah. `AnonRateThrottle` will go first before `UserRateThrottle`
The throttling works as a route function decorator and is not part of the ninja `Operation` core which now makes it difficult for me to give you your decided solution

**Comment by eadwinCode** [comment]
I have a solution for you for now, while I think for a more better solution
```python



@api_controller(
    "users",
    tags=["Users"],
    auth=LoginAuthentication(), # this is custom BasicAuth
    permissions=[],
)
class UserController(ControllerBase):
    throttling_classes = [AnonRateThrottle, UserRateThrottle]
    
    @http_get("/", response=List[UserSchema])
    def get_users(self, request):
        """
        List descendant users
        """
        user = request.auth
        return user.get_descendants(include_self=True)
```

**Comment by eadwinCode** [comment]
@MGotkowski for that example to work, you need to upgrade to ninja_extra v0.19.8
