### ISSUE TITLE
Using Custom Pagination in Django Ninja

### ISSUE THREAD

**Issue by ddahan** [eadwinCode/django-ninja-extra#99]
Hi there!
I think the `PageNumberPaginationExtra` is something I need. I tried to add it in two unsuccessful ways:
- First by installing this package. Rapidly, I noticed I have to make multiple changes to my code, and I don't especially want to change the whole ninja mechanism which works well for me. I don't need class based endpoints, and other stuff. I'd like to avoid the dependency.
- Then I tries to copy paste Pagination code and use directly in my code. Again, I had weird errors, suggesting that maybe I can't use this code as it, outside of ninja extra.

What should I do to "extract" `PageNumberPaginationExtra` properly from Django ninja extra?
Thanks for your help.

**Comment by eadwinCode** [comment]
@ddahan The feature is tied to the package but you understand pagination in Django Ninja, you should be able to implement something similar to `PageNumberPaginationExtra`

**Comment by ddahan** [comment]
TBH I didn't understand why the PageNumberPagination was so complex in this package code source. There must be a reason, but out of my knowledge.

Here is a working custom `PageNumberPagination` implementation example without this package:

```python
from typing import Any

from ninja import Field, Schema
from ninja.pagination import PaginationBase


class MyPageNumberPagination(PaginationBase):
    class Input(Schema):
        page: int = Field(1, ge=1)

    class Output(Schema):
        nb_items: int
        nb_pages: int
        page: int
        previous_page: str | None
        next_page: str | None

    def __init__(self, page_size: int = 100, **kwargs):
        self.page_size = page_size
        super().__init__(**kwargs)

    def paginate_queryset(self, queryset, pagination: Input, request) -> Any:
        offset = (pagination.page - 1) * self.page_size
        nb_items = self._items_count(queryset)
        next_page, previous_page = None, None
        if pagination.page > 1:
            previous_page = request.build_absolute_uri(
                request.path + "?page=" + str(pagination.page - 1)
            )
        if offset + self.page_size < nb_items:
            next_page = request.build_absolute_uri(
                request.path + "?page=" + str(pagination.page + 1)
            )
        return {
            "nb_items": nb_items,
            "nb_pages": (nb_items + self.page_size - 1) // self.page_size,
            "page": pagination.page,
            "previous_page": previous_page,
            "next_page": next_page,
            "items": queryset[offset : offset + self.page_size],
        }

```

**Comment by eadwinCode** [comment]
And how are you using `MyPageNumberPagination`

**Comment by ddahan** [comment]
@eadwinCode I updated my previous answer to add a usage example.

**Comment by eadwinCode** [comment]
@ddahan You need to fix your output schema `MyPageNumberPagination`
```python
    class Output(Schema):
        nb_items: int
        nb_pages: int
        page: int
        previous_page: str | None
        next_page: str | None
```
The `page` field needs to be defined

Once you fix that, the next thing is to resolve the response schema in your endpoint
```python
@router.get("", response=MyPageNumberPagination.Output[MySchema])
@paginate(MyPageNumberPagination, page_size=10)
def list_badges(request):
    return Badge.objects.all()
```
Read more on [Pydantic Generics](https://docs.pydantic.dev/latest/concepts/types/#generics)

**Comment by ddahan** [comment]
> The `page` field needs to be defined properly... What you return from `paginate_queryset` shows, page field is not an int field

Can you elaborate on this? It is the same `page` variable that I defined myself in:

```
class Input(Schema):
        page: int = Field(1, ge=1)
```

As it is defined, it's an `int` that must be greater or equal at 1. What's wrong here?

> the next thing is to resolve the response schema in your endpoint

You're right. I forgot to change the response type. I'd have expected this to create an error, but it works as is.

**Comment by eadwinCode** [comment]
@ddahan oh it's an oversight... I meant the items... The output schema is not having the items field defined
